version: 2

workflows:
  version: 2
  test-or-publish:
    jobs:
      - test:
          filters:
            branches:
              ignore: /^publish/
      - publish:
          filters:
            branches:
              only: /^publish/

defaults: &defaults
  working_directory: ~/repo
  docker:
    - image: circleci/node:latest

jobs:
  test:
    <<: *defaults  
    steps:
      - checkout
      - restore_cache:
          keys:
          - v1-dependencies-{{ checksum "package.json" }}
          - v1-dependencies-
      - run: mkdir public
      - run: cp -r assets public
      - run: yarn install
      - run: yarn run webpack --mode=production
      - save_cache:
          paths:
            - node_modules
          key: v1-dependencies-{{ checksum "package.json" }}
  publish:
    <<: *defaults
    steps:
      - checkout
      - restore_cache:
          keys:
          - v1-dependencies-{{ checksum "package.json" }}
          - v1-dependencies-
      - run: mkdir public
      - run: cp -r assets public
      - run: yarn install
      - run: yarn run webpack --mode=production
      - save_cache:
          paths:
            - node_modules
          key: v1-dependencies-{{ checksum "package.json" }}
